# Generated by Django 2.2.4 on 2020-06-07 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skeleton',
            old_name='produc_description',
            new_name='product_description',
        ),
    ]
